name: meal_planner
description: Application de planification de repas

environment:
  sdk: '>=3.0.0 <4.0.0' 
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  # Gestion d'état
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6

  # Navigation
  go_router: ^10.0.0
  # HTTP client
  dio: ^5.3.0
  # Stockage local
  shared_preferences: ^2.2.0
  # Gestion des formulaires
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^11.0.0
  # UI
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  # Utilitaires
  intl: ^0.19.0
  logger: ^1.4.0
  image_picker: ^1.0.0

  # Animations
  lottie: ^2.5.0

# Ajoutez ici d'autres sections comme dev_dependencies si nécessaire

flutter:
  # Utilisez Material Design
  uses-material-design: true
  
  # Ajoutez ici vos assets si nécessaire
  # assets:
  #   - assets/images/
  
  # Configuration des polices
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf